import type { Metadata } from "next";
import { LegalDocument } from "../components/legal-document";

export const metadata: Metadata = {
  title: "Privacy Policy | Adem Eren Decoration",
  description:
    "Privacy Policy for Adem Eren Decoration sample requests, project inquiries, and website communication.",
};

const privacySections = [
  {
    title: "Information we collect",
    body: [
      "We collect information that you choose to send to us when you request samples, ask for a project quote, contact us through WhatsApp, or use the website contact form.",
      "This may include your name, phone number, email address, project location, preferred SPC floor or wall panel collection, project notes, and message history.",
    ],
    items: [
      "Contact details you provide for communication.",
      "Project details needed for samples, quantities, installation planning, and quotes.",
      "Basic technical information such as browser type, page visits, IP address, and security logs generated by hosting or website providers.",
    ],
  },
  {
    title: "How we use information",
    body: [
      "We use the information to respond to your inquiry, prepare sample requests, plan project quantities, coordinate installation discussions, improve the website, and protect the website from misuse.",
      "We do not use the website as an online checkout store. Project prices, sample details, measurements, payment terms, and installation timing are handled through direct communication.",
    ],
  },
  {
    title: "Sharing information",
    body: [
      "We do not sell personal information. We may share the information only when it is needed to answer your request, provide a service, operate the website, or meet a legal requirement.",
    ],
    items: [
      "Installation teams, suppliers, logistics providers, or project partners when needed for your project.",
      "Website hosting, security, analytics, messaging, or form service providers.",
      "Authorities or professional advisers when required by applicable rules or to protect our rights.",
    ],
  },
  {
    title: "Cookies and external links",
    body: [
      "The website may use basic technical cookies, server logs, or similar technologies for operation, security, performance, and visitor measurement if those tools are enabled.",
      "The website links to third-party services such as WhatsApp and Kermit Floor product pages. Those services have their own privacy practices, and their websites are not controlled by Adem Eren Decoration.",
    ],
  },
  {
    title: "Retention and choices",
    body: [
      "We keep inquiry and project information only for as long as it is useful for communication, project planning, business records, or legal requirements.",
      "You may contact us to ask for access, correction, deletion, or to stop receiving direct project communication. Some records may be kept when required for legitimate business or legal reasons.",
    ],
  },
  {
    title: "Contact",
    body: [
      "For privacy questions or requests, contact Adem Eren Decoration through the website contact section or the WhatsApp button on the website.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalDocument
      description="This Privacy Policy explains how we handle information for website visitors, sample requests, project inquiries, and direct communication."
      lastUpdated="June 5, 2026"
      sections={privacySections}
      title="Privacy Policy"
    />
  );
}
